language: python
python:
  - 3.5
  - 3.6
  - 3.7
before_install:
  - sudo apt-get update
  - sudo apt install pep8
install:
  - pip install unittest2
  - pip install pep8
before_script: cd root/tests
script: sh test_all.sh
