language: python
python:
  - 3.5
  - 3.6
  - 3.7
before_install:
  - sudo apt-get update
  - sudo apt-get install pycodestyle
install:
  - pip install unittest2
before_script: cd root/tests
script: sh test_all.sh
